/// Flutter icons LazaIcons
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  LazaIcons
///      fonts:
///       - asset: fonts/LazaIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class LazaIcons {
  LazaIcons._();

  static const _kFontFam = 'LazaIcons';
  static const String? _kFontPkg = null;

  static const IconData adidas = IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fila = IconData(0xe81e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData vector = IconData(0xe822, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData voice22 = IconData(0xe825, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search22 = IconData(0xe826, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bag2 = IconData(0xe827, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData puma_logo_1 = IconData(0xe828, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData menu2 = IconData(0xe829, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
